<a href="https://colab.research.google.com/github/shaanvithabandewar/data_science_assignmets/blob/main/assignment_11_recommended_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load the anime dataset
anime_df = pd.read_csv('anime.csv')

# Display basic information and the first few rows of the dataset
anime_info = anime_df.info()
anime_head = anime_df.head()

anime_info, anime_head

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

(None,
    anime_id                              name  \
 0     32281                    Kimi no Na wa.
 1      5114  Fullmetal Alchemist: Brotherhood
 2     28977                          GintamaÂ°
 3      9253                       Steins;Gate
 4      9969                     Gintama&#039;

                                                genre   type episodes  rating  \
 0               Drama, Romance, School, Supernatural  Movie        1    9.37
 1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26
 2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25
 3                                   Sci-Fi, Thriller     TV       24    9.17
 4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16

    members
 0   200630
 1   793665
 2   114262
 3   673572
 4   151266  )

In [ ]:
# Handle missing values
# Fill missing 'genre' and 'type' with 'Unknown'
anime_df['genre'].fillna('Unknown', inplace=True)
anime_df['type'].fillna('Unknown', inplace=True)

# For 'rating', fill missing values with the mean rating
mean_rating = anime_df['rating'].mean()
anime_df['rating'].fillna(mean_rating, inplace=True)

# Verify that there are no more missing values
missing_values = anime_df.isnull().sum()

missing_values

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler


anime_df = pd.read_csv('anime.csv')

# Data Preprocessing

# Fill missing 'rating' values with the mean rating
anime_df['rating'].fillna(anime_df['rating'].mean(), inplace=True)

# Fill missing 'genre' and 'type' values with 'Unknown'
anime_df['genre'].fillna('Unknown', inplace=True)
anime_df['type'].fillna('Unknown', inplace=True)

# Feature Extraction
anime_df['genre'] = anime_df['genre'].str.split(', ')
anime_genre_encoded = anime_df['genre'].str.join('|').str.get_dummies()

# Normalize the 'rating' feature
scaler = StandardScaler()
anime_df['rating_normalized'] = scaler.fit_transform(anime_df[['rating']])

# Combine the one-hot encoded genres and normalized ratings into a single DataFrame
anime_features = pd.concat([anime_genre_encoded, anime_df['rating_normalized']], axis=1)

# Display the first few rows of the transformed dataset
anime_features.head()

,Action,Adventure,Cars,Comedy,Dementia,Demons,Drama,Ecchi,Fantasy,Game,...,Space,Sports,Super Power,Supernatural,Thriller,Unknown,Vampire,Yaoi,Yuri,rating_normalized
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,2.847535
1,1,1,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,2.739380
2,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2.729547
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,2.650889
4,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2.641057